[book]
title = "Програмски језик C"
authors = ["Velimir Radlovački"]
language = "sr"
multilingual = false
src = "src"

[output.html]
mathjax-support = true

[preprocessor.katex]
renderers = ["html"]
no-css = false
include-src = false
block-delimiter = {left = "$$", right = "$$"}
inline-delimiter = {left = "$", right = "$"}
